version: '3.1'

services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - "./create.sql:/home/create.sql"
        - "./populate.sql:/home/populate.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root123
